### ISSUE TITLE
Провести оптимизацию тасков

### ISSUE THREAD

**Issue by zoxon** [zoxon/gulp-front#14]
В связи с долгим прогревом системы и сложностью ориентации по файлу, нужно провести разбивку gulpfile.js на отдельные таски и подгружать в зависимости от необходимости.

**Comment by meff34** [comment]
Добрый день. Есть [вот такая](github.com/meff34/gulp) реализация оптимизации, на основе скринкаста Ильи Кантора и gulp-load-plugins. Плюс кое-какие свои наработочки, в частности, отдельный helper.js.

Могу посидеть вечерочком, переписать.

**Comment by zoxon** [comment]
@meff34 
Добрый день.
Было бы круто, сам хотел что то подобное запилить.
Собственно идея оптимизации возникла после просмотра этого самого скринкаста.

**Comment by meff34** [comment]
@zoxon 
Форк я сделал, ждите pull request в течение дней двух-трёх.

**Comment by meff34** [comment]
Константин, мы можем связаться в каком-нибудь мессенджере или соцсети? Боюсь, без консультации не смогу обойтись.

**Comment by zoxon** [comment]
Можно в gitter https://gitter.im/zoxon/gulp-front
