### ISSUE TITLE
Анимация аккордеона при смещении соседних DOM элементов лагает

### ISSUE THREAD

**Issue by amywoodehy** [zoxon/gulp-front#24]
windows 10 1607.15046.0
Chrome: Version 56.0.2924.87 (64-bit)

**Comment by zoxon** [comment]
Есть предложения как это решить?

**Comment by amywoodehy** [comment]
Если честно, то нет

**Comment by amywoodehy** [comment]
Но в бутстрапе это решили транзишинами покрыть https://github.com/twbs/bootstrap/issues/11483

**Comment by zoxon** [comment]
Лагает не из-за этого, а из-за репейнта контнента снизу. Ну и jquery анимации не сильно производительные.
Для transition нужно знать итоговую высоту контента

**Comment by amywoodehy** [comment]
Да, действительно. Со спойлером такая же проблема
