### ISSUE TITLE
Иконки в кнопках - разного размера

### ISSUE THREAD

**Issue by anmaslov** [zoxon/gulp-front#25]
Если добавить svg иконку кнопке, при разных размерах иконки и кнопки, размеры у иконки всегда одинаковые.

**Comment by anmaslov** [comment]
#26

**Comment by zoxon** [comment]
Размеры иконки одинаковые по тому что они явно задаются [в шаблоне](https://github.com/zoxon/gulp-front/blob/master/source/static/styles/templates/icons-template.styl#L26)
Решение которое вы предлагаете больше похоже на костыль. Нужно решать использовать размеры иконок по умолчанию или нет.

**Comment by anmaslov** [comment]
А как быть с разными размерами кнопок? Для самой маленькой и самой большой кнопки размер иконки будет одинаковый.

**Comment by zoxon** [comment]
Думаю правильней будет задать стандартные размеры иконкам, так как это отдельный блок.

```styl
.icon
	&_size_normal
		size 16px
		
	&_size_extra-large
		size 20px
		
	&_size_large
		size 18px
		
	&_size_small
		size 14px
		
	&_size_extra-small
		size 12px
```

Ну и другие модификаторы тоже можно использовать.

Либо использовать элемент в вместо тега

```styl
button-size(padding, font-size, line-height)
	padding padding
	font-size font-size
	if line-height
		line-height line-height
	
	.button__icon
		size font-size
```

А скорее всего удобнее будет комбинировать эти подходы.
Вообщем надо пробовать и экспериментировать, я пока с такой ситуацией не встречался.

**Comment by anmaslov** [comment]
ок, для меня второй подход более предпочтительней. Огромное спасибо за проделанную работу!
