### ISSUE TITLE
Не могу запустить

### ISSUE THREAD

**Issue by Ferym26** [zoxon/gulp-front#44]
Win10
npm -v > 5.3.0
gulp -v >  CLI version 2.0.0, Local version 4.0.0-alpha.3

при запуске **npm start** получаю http://joxi.ru/823oWPjI6YGzD2

**Comment by zoxon** [comment]
https://github.com/twolfson/pixelsmith/issues/10

**Comment by Ferym26** [comment]
обновил gulp до 4.0.0
проблема осталась таже

**Comment by zoxon** [comment]
Удалите папку node_modules, и установить через yarn.
```sh
$ rm -rf node_modules/
$ yarn install
$ yarn start
```

Можете попробовать понизить версию gulp.spritesmit, или исправить [ошибку в pixelsmith](https://github.com/twolfson/pixelsmith/issues/10)

**Comment by Ferym26** [comment]
установка через yarn помогла. всё работает, спасибо
