### ISSUE TITLE
Вопрос про emitty

### ISSUE THREAD

**Issue by Ferym26** [zoxon/gulp-front#45]
Как реализована работа с emitty и работает ли инкрементальная сборка pug?
кроме таска watch.js больше нигде концов не нашел, но этого недостаточно по офф доке emitty. 
поясните плз

**Comment by zoxon** [comment]
emitty так и не заработал нормально, сначала добавил потом удалил
вот вторая часть https://github.com/zoxon/gulp-front/commit/b5cecce31327e6a068232f3c34326cd14a58d9ef, можете поэкспериментировать

**Comment by Ferym26** [comment]
не очень глубоко шарю, но может дело в этом:
`emitty: require('emitty').setup('path', 'pug', **{  makeVinylFile: true})**`
в моём [сборщике ](https://github.com/Ferym26/Adc-template-LP/tree/v-gulp4) работает

**Comment by zoxon** [comment]
Спасибо попробую, я только за оптимизацию
