### ISSUE TITLE
"npm install" - не ставит зависимости

### ISSUE THREAD

**Issue by Sergeniy** [Zoxon/gulp-front#5]
Скрин - http://joxi.ru/12MQk4qtkJel2J

**Comment by Zoxon** [comment]
У меня и мох коллег все ставится, тесты на этой же версии node.js проходит успешно.
https://travis-ci.org/Zoxon/gulp-front

Так что это проблема на вашем компютере.

Судя по скрину, не докачался один компонент пакета browser-sync.
Попробуйте опять выполнить `npm install` либо удалить пакет browser-sync `npm uninstall browser-sync` и установить его `npm install browser-sync`.

**Comment by Sergeniy** [comment]
Помогло "npm install browser-sync", спасибо.
