### ISSUE TITLE
Не могу подключить jQuery

### ISSUE THREAD

**Issue by trixter5** [zoxon/gulp-front#54]
Понадобился range slider(period) для фильтра по ценам. Было бы быстрее подключить на jQuery готовый плагин. Не могу через модуль подключить jquery  так, чтобы все работало. Либо  ошибки, либо ничего. 
Последний вариант без ошибок так
Модуль 
`import {jQuery as _$} from "jquery"
import ionRangeSlider from "ion-rangeslider"

export default () => {
  _$, ionRangeSlider
}`

main.js
`import rangeSlider from "@/modules/range-interval/range-interval";`

`(function(_$, ionRangeSlider) {
  _$('.rangeSlider').ionRangeSlider();
});`

Буду признателен з аподсказку

**Comment by zoxon** [comment]
Все намного проще чем кажется

```js
// slider.js
import $ from "jquery";
import "ion-rangeslider"; // делать здесь named import бессмысленно, импортируем глобально

// это простейший вариант модуля
// экспортируем функцию
export default () => $("#example_id").ionRangeSlider();

// если нужно передавать параметры можно сделать так
// лучше сразу так делать, это на много гибче
export default (selector, options) => {
  const defaultOptions = {
    grid: true
  };
  const mergedOptions = Object.assign({}, defaultOptions, options);

  return $(selector).ionRangeSlider(mergedOptions);
}
```

```js
// main.js
import Slider from "@/modules/slider/slider";
Slider("#slider", {
  type: "double",
  min: 0,
  max: 1000,
  from: 200,
  to: 500,
  grid: false
})
```

```styl
// slider.styl
@import "ion-rangeslider/css/ion.rangeSlider.css"

// ваши стили
```

**Comment by zoxon** [comment]
@trixter5 у вас все получилось?

**Comment by trixter5** [comment]
@zoxon, да все супер! Спасибо за такой быстрый ответ. Ваша сборка, лучшая из того, что я видел для верстки. По ней можно js учить.

**Comment by zoxon** [comment]
Спасибо, что пользуетесь
