### ISSUE TITLE
browser-sync

### ISSUE THREAD

**Issue by blanzh** [Zoxon/gulp-front#7]
как у тебя работает этот кусок?
мне пришлось указывать путь от корня
И то что 2 раза File Changed это нормально?
http://n9922.ru/s/coX7.png

```javascript
// Локальный сервер
gulp.task('browser-sync', function () {
	browserSync.init([
		'*.html',
		'css/*.css',
		'**/*.{png,jpg,svg}',
		'js/*.js',
		'fonts/*.{eot,woff,woff2,ttf}'
	], {
		open: true,
		server: { baseDir: './public' }
	});
});
```

**Comment by Zoxon** [comment]
Отлично работает. Тестировалось лично на windows 7 x64 node.js v0.12.4

> мне пришлось указывать путь от корня

Все правильно


> И то что 2 раза File Changed это нормально?

А что тут такого, пусть 2 раза.

**Comment by blanzh** [comment]
Дак как у тебя работает если у тебя не указан путь через ./build

пятница, 26 июня 2015 г. пользователь Velichko Konstantin написал:

**Comment by Zoxon** [comment]
![2015-06-27 11-19-03 gulp](https://cloud.githubusercontent.com/assets/3866196/8390594/636b252c-1cbe-11e5-8237-84de4a352ebb.png)
Вот спецом запустил

**Comment by blanzh** [comment]
Это запускается с когда изменяешь? Вотчер ловит по таким путям файлы?

суббота, 27 июня 2015 г. пользователь Velichko Konstantin написал:

**Comment by Zoxon** [comment]
Да, все отлично работает.
Возможно поставилась старая версия из кеша.
Попробуй почистит кеш  `npm cache clear`, потом удалить все локальные пакеты, например через Total Commander и установить все зависимости заново.

**Comment by blanzh** [comment]
И ведь помогло. Не радует такая нестабильность :/ зависимости не
переопределял установил все из исходного packages и заработало

суббота, 27 июня 2015 г. пользователь Velichko Konstantin написал:

**Comment by Zoxon** [comment]
Вот такая она модульная архитектура.
